server:
  port: ${PORT:8080}

spring:
  cloud:
    gcp:
      sql:
        enabled: true
        instance-connection-name: ${CLOUD_SQL_CONNECTION_NAME}
        database-name: ${DB_NAME:ecommerce_db}
  datasource:
    username: ${DB_USER:ecommerce_app}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info