name: Deploy Monolith to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy-static:
    name: Deploy Static Files to GCS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Sync Files to Cloud Storage Bucket
        run: |
          gcloud storage rsync . gs://monolith-static-prasadaraodarla \
            --recursive \
            --exclude=".git/*|.github/*|README.md"